config/routes.rb
Rails.application.routes.draw do
  
  root 'works#index'

  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users, only: [:new, :create, :show, :update]
  resources :works, only: [:index, :new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: { minimum: 5, maximum: 25 }
  validates :fullname, presence: true, length: { minimum: 6, maximum: 100 }

  has_many :works, foreign_key: :author_id

  has_many :followings, class_name: 'Following',
                        foreign_key: 'follower_id',
                        dependent: :destroy

  has_many :reverse_followings, class_name: 'Following',
                                foreign_key: 'followed_id',
                                dependent: :destroy

  has_many :following, through: :followings, source: :followed
  has_many :followers, through: :reverse_followings, source: :follower

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  scope :recently_created, -> { where("created_at >= #{Date.today - 2}") }
  mount_uploader :coverimage, PictureUploader
  mount_uploader :photo, PictureUploader
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :author, class_name: 'User'
  scope :sorted_by_most_recent, -> { order(created_at: :desc) }
  validates :picture, presence: true
  mount_uploader :picture, PictureUploader

  validates :text, length: { maximum: 255 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include FollowingsHelper

  private

  # Confirms a logged-in user.
  def logged_in_user
    store_location unless logged_in?
    flash[:info] = 'Please log in.' unless logged_in?
    redirect_to login_url unless logged_in?
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :logged_in_user

  def create
    follow = Following.new(follower_id: current_user.id, followed_id: following_params)
    if follow.save
      flash[:success] = 'Following User'
    else
      flash[:danger] = "You can't follow the User"
    end
    redirect_to root_path
  end

  private

  def following_params
    params.require(:followed_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(session_params)
    if !user.nil?
      remember(user)
      flash[:info] = 'User Logged in'
      redirect_to root_path
    else
      flash.now[:danger] = 'User doesn\'t exist'
      render 'new'
    end
  end

  def destroy
    if logged_in?
      log_out
      flash[:info] = 'User Logged out.'
    else
      flash[:danger] = "User wasn't even logged in."
    end
    redirect_to root_url
  end

  private

  def session_params
    params.require(:session).permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[show update]
  before_action :correct_user, only: [:update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User Created'
      redirect_to login_path
    else
      flash[:danger] = 'User Creation failed'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = 'User updated'
      redirect_to current_user
    else
      flash[:danger] = 'User update failed'
      render 'show'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :fullname, :coverimage, :photo)
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :logged_in_user, only: %i[create index]

  def index
    @work = Work.new
  end

  def create
    @work = current_user.works.build(work_params)
    if @work.save
      flash[:success] = 'Work created!'
      redirect_to root_path
    else
      flash.now[:danger] = "Couldn\'nt create work"
      render 'index'
    end
  end

  private

  def work_params
    params.require(:work).permit(:text, :picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
  def following
    current_user.following.ids.empty? ? 0 : current_user.following.ids
  end

  def followers(user)
    user.followers.ids.empty? ? 0 : user.followers.ids
  end

  def following?(user)
    !current_user.following.include?(user)
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
    def remember(user)
      # user.remember
      cookies.permanent.signed[:username] = user.username
      # cookies.permanent[:remember_token] = user.remember_token
      @current_user = user
    end
  
    # Logs in the given user.
    def log_in(user)
      session[:username] = user.username
    end
  
    def current_user
      @current_user ||= User.find_by(username: cookies.signed[:username])
    end
  
    def current_user=(user)
      @current_user = user
    end
  
    def forget(user)
      cookies.delete(:username)
    end
  
    def log_out
      forget(current_user)
    end
  
    def logged_in?
      !current_user.nil?
    end

    # Stores the URL trying to be accessed.
    def store_location
      session[:forwarding_url] = request.original_url if request.get?
    end

  end
  

app/helpers/users_helper.rb
module UsersHelper
  def current_name
    current_user.fullname
  end

  def timeline_user(user)
    works = user.works
    render partial: 'shared/timeline', locals: { works: works }
  end

  def timeline_followers(user)
    user_followers = User.all.ordered_by_most_recent.where('id IN (?)', followers(user))

    render partial: 'users/timeline_followers', locals: { users: user_followers }
  end

  def current_user?(user)
    current_user == user
  end

  def picture_form(user, simbol)
    render partial: 'users/picture_form', locals: { user: user, simbol: simbol } if current_user? user
  end

  def follow_form(user)
    render partial: 'users/follow_form', locals: { user: user } if following? user
  end
end

app/helpers/works_helper.rb
module WorksHelper
  def timeline_works
    works ||= Work.all.sorted_by_most_recent.where("author_id IN (#{current_user.id},?)", following)

    render partial: 'shared/timeline', locals: { works: works }
  end

  def timeline_follows
    @timeline_follows ||= User.all.ordered_by_most_recent.where("id NOT IN (#{current_user.id},?)", following)
    render @timeline_follows
  end
end

app/views/layouts/_navbar.html.erb
<nav>
    <% if logged_in? %>
    <h1> <%= current_name %> </h1>
    <ul>        
        <li>
        <%= link_to 'Following', '#'%>
        </li>
        <li>
        <%= link_to 'Followers', '#' %>
        </li>
        <li>
        <%= link_to 'HOME', '#' %>
        </li>
        <li>
        <%= link_to 'PROFILE', '#' %>
        </li>
        <li>
        <%= link_to "Log out", logout_path, method: :delete %>
        </li>
    <% else %>
    <ul>
        <li><%= link_to "Log in", login_path %></li>
        <li><%= link_to "Sign up", signup_path %></li>
    <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Inter:300,400,500&display=swap" rel="stylesheet">
  </head>

  <body class="d-flex w-100">
    <%= render 'layouts/navbar' %>
    <% if logged_in? %>
    <main class= "float-left w-85">
    <div class='bg-primary h-80 w-100 py-20 pt-10 d-flex justify-content-between'>
      <img class="photo" src="https://maru-workagram.s3.us-east-2.amazonaws.com/uploads/assets/hammer-64.png">
      <%= link_to "Log out", logout_path, method: :delete, class: "text-white pt-10" if logged_in?%> 
    <% else %>
    <main class= "float-left w-100">
    <div class='bg-primary h-80 w-100  py-20 pt-10 d-flex justify-content-between'>
      <img class="photo" src="https://maru-workagram.s3.us-east-2.amazonaws.com/uploads/assets/hammer-64.png">
      <div>
        <%= link_to "Log in", login_path, class: "text-white pt-10" %>
        <%= link_to "Sign up", signup_path, class: "text-white pl-10 pt-10" %>
      </div>
     <% end %>
    </div>
    <% flash.each do |message_type, message| %>
      <p class="alert alert-<%= message_type %>"><%= message %></p>
    <% end %>
    <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="error">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_timeline.html.erb
<% works.each do |work| %>
<li>
  <div class="d-flex w-100 pt-10">
    <%= image_tag work.author.photo.url, class: "photo" if work.author.photo? %>
    <%= link_to work.author.fullname, user_path(work.author), class: "text-body pt-10 pl-5" %>    
  </div>
  <br>
  <%= image_tag work.picture.url, class: "w-100 float-left pt-10 mb-10" %>
  <br>
  <p class="pt-20 text-muted w-100">
    <%= work.text %>
  </p>
</li>
<% end %>

app/views/users/_follow_form.html.erb
<%= form_for(current_user.followings.build) do |f| %>
  <div>
    <%= hidden_field_tag :followed_id, user.id %>
  </div>
  <%= f.submit "Follow", class: "btn btn-primary" if current_user != user && following?(user) %>
<% end %> 

app/views/users/_picture_form.html.erb
<%= form_for(user) do |f|  %>
  <%= render 'shared/errors', object: f.object %>
    <span class="d-flex w-100">
      <%= f.file_field simbol, accept: 'image/jpeg,image/gif,image/png', class: "text-center w-75 float-left" %>
      <%= f.submit "Update #{simbol}", class: "btn btn-primary float-left" %>
    </span>
<% end %>

app/views/users/_timeline_followers.html.erb
<% users.each do |user| %>
    <li>
    <div>
      <div>
        <%= image_tag user.photo.url, class: "photo img-circle float-left" if user.photo? %>
        <%= link_to user.fullname, user_path(user) %>
      </div>
    </div>
    <%= form_for(current_user.followings.build) do |f| %>
        <div><%= hidden_field_tag :followed_id, user.id %></div>
        <%= f.submit "Follow", class: "btn btn-primary"  if current_user != user && following?(user)%>
    <% end %>
    </li>
<% end %>

app/views/users/_user.html.erb
<li>
  <div class="pt-10">
    <%= image_tag user.photo.url, class: "photo img-circle float-left" if user.photo? %>
    <%= link_to user.fullname, user_path(user), class: "pl-5" %>
  </div>
  <%= form_for(current_user.followings.build) do |f| %>
    <div><%= hidden_field_tag :followed_id, user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary ml-5" if current_user != user && following?(user)%>
  <% end %>
</li>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div>
  <div>
    <%= form_for @user, url: {action: "create"} do |f| %>
      <%= render 'shared/errors', object: f.object %>

      <%= f.label :username %>
      <%= f.text_field :username%>

      <%= f.label 'Full name' %>
      <%= f.text_field :fullname %>

      <%= f.submit "Create my account" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<section class="float-left border-right">
  <%= image_tag @user.coverimage.url.to_s, class: "cover_img w-100" if @user.coverimage? %>
  <%= picture_form(@user, :coverimage) %>
  <article>
    <h5 class="text-muted">ALL WORKS / NO REPLIES</h5>
      <ul class="nav-border-t">
      <%= timeline_user(@user) %>
      </ul>
  </article>
</section>

<aside class="float-left pl-10">
  <div class="text-center centered w-100">
  <%= image_tag @user.photo.url, class: "mt-10 w-50 img-circle text-center" if @user.photo? %>
  <h5 class="text-center"><%= @user.fullname.upcase %></h5>
  <%= picture_form(@user, :photo) %>
  <%= follow_form(@user) %>
  </div>
  <ul class="d-flex w-100 border-top border-bottom mt-10">  
    <li class="float-left w-33 text-center border-right">
      <h3><%= @user.works.count%></h2> 
      <p class="text-muted">Works</p>
    </li>      
    <li class="float-left w-33 text-center border-right">
      <h3><%= @user.following.count%></h2> 
      <p class="text-muted">Following</p>
    </li>
    <li class="float-left w-33 text-center">
      <h3><%= @user.followers.count %></h3>
      <p class="text-muted">Followers</p>
    </li>
  </ul>

  <h5 class="text-muted">FOLLOWED BY</h5>
  <ul>
  <%= timeline_followers(@user) %>
  </ul>
</aside>

app/views/works/_work.html.erb
<li >
<div>
  <div>
    <%= link_to work.author.fullname, user_path(work.author) %>
  </div>
</div>
<p>
  <%= work.text %>
</p>
</li>

app/views/works/create.html.erb
<h1>Works#create</h1>
<p>Find me in app/views/works/create.html.erb</p>

app/views/works/destroy.html.erb
<h1>Works#destroy</h1>
<p>Find me in app/views/works/destroy.html.erb</p>

app/views/works/index.html.erb
<section class="float-left">
  <article>
    <h5 class="text-muted">WORKAGRAM SOMETHING</h5>
    <%= form_for @work, url: {action: "create"} do |f| %>
      <%= render 'shared/errors', object: f.object %>
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: "pl-5" %>
      <%= f.text_field :text, :placeholder => "New comment", class: "pl-5 ml-5" %>
      <%= f.submit "Post", class: "btn btn-primary" %>
    <% end %>
  </article>
  <article>
  <h5 class="text-muted">NEW WORKAGRAMS</h5>
      <ul class="nav-border-t pt-10">
      <%= timeline_works %>
      </ul>
  </article>   
</section>

<aside class="float-left">
<h5 class="text-muted pt-10">WHO TO FOLLOW</h5>
  <ul class="nav-border-t pt-10">
    <%= timeline_follows %>
  </ul>
</aside>

app/views/works/new.html.erb
<h1>Works#new</h1>
<p>Find me in app/views/works/new.html.erb</p>